# Generated by Django 4.0.3 on 2022-03-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_orders_order_orders_status_alter_order_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orders_status',
            new_name='order_status',
        ),
    ]
